from erpnext.accounts.doctype.payment_entry.payment_entry import PaymentEntry as _PaymentEntry
from token_enhancement.overrides.payment_entry_override import OverridenPaymentEntry as _OverridenPaymentEntry

from erpnext.stock.doctype.delivery_note.delivery_note import DeliveryNote as _DeliveryNote
from token_enhancement.overrides.delivery_note_override import OverriddenDeliveryNote as _OverriddenDeliveryNote

_PaymentEntry.setup_party_account_field = _OverridenPaymentEntry.setup_party_account_field
_PaymentEntry.validate = _OverridenPaymentEntry.validate
_PaymentEntry.on_submit = _OverridenPaymentEntry.on_submit
_PaymentEntry.on_cancel = _OverridenPaymentEntry.on_cancel
_PaymentEntry.redeem_token_update = _OverridenPaymentEntry.redeem_token_update
_PaymentEntry.validate_payment_type = _OverridenPaymentEntry.validate_payment_type
_PaymentEntry.validate_bank_accounts = _OverridenPaymentEntry.validate_bank_accounts
_PaymentEntry.set_token_references = _OverridenPaymentEntry.set_token_references
_PaymentEntry.validate_token_references = _OverridenPaymentEntry.validate_token_references
_PaymentEntry.validate_duplicate_token_entries = _OverridenPaymentEntry.validate_duplicate_token_entries
_PaymentEntry.validate_allocated_amount_for_tokens = _OverridenPaymentEntry.validate_allocated_amount_for_tokens
_PaymentEntry.set_amounts_for_tokens = _OverridenPaymentEntry.set_amounts_for_tokens
_PaymentEntry.set_total_allocated_amount_tokens = _OverridenPaymentEntry.set_total_allocated_amount_tokens
_PaymentEntry.set_difference_amount = _OverridenPaymentEntry.set_difference_amount
_PaymentEntry.set_title = _OverridenPaymentEntry.set_title
_PaymentEntry.set_remarks_token_pe = _OverridenPaymentEntry.set_remarks_token_pe
_PaymentEntry.add_party_gl_entries = _OverridenPaymentEntry.add_party_gl_entries
_PaymentEntry.add_bank_gl_entries = _OverridenPaymentEntry.add_bank_gl_entries

_DeliveryNote.validate_tokens = _OverriddenDeliveryNote.validate_tokens
_DeliveryNote.validate_duplicate_token_entries = _OverriddenDeliveryNote.validate_duplicate_token_entries
_DeliveryNote.issue_token_update = _OverriddenDeliveryNote.issue_token_update
_DeliveryNote.validate = _OverriddenDeliveryNote.validate
_DeliveryNote.on_submit = _OverriddenDeliveryNote.on_submit
_DeliveryNote.on_cancel = _OverriddenDeliveryNote.on_cancel
